[package]
name = "mfn-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Core data and control nodes for miniflow"

[dependencies]
inventory = "0.3.24"
mf-runtime.workspace = true
mf-telemetry.workspace = true
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
